name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Menjalankan setiap hari

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@main
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist
